allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  df86e976-74ee-4e6a-87ef-b81d9ba7e9b3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T00:58:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 06365e39-2e91-4e8b-a2da-2d035a771b1c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-03-23T22:23:08+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c3444894-3716-4142-8821-7a9460bcb16b
            userCondition: null
          -
            dateAdded: '2025-05-07T18:33:11+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f6c3037a-a389-45dc-a0cd-c448e9e6223e # Staff Contact
            handle: null
            instructions: 'Choose a Staff member to be the main point of contact.'
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd4f7df3-552f-43bd-a6f3-d1e253077a73
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-23T22:23:41+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 043d0646-d357-4201-8710-f29cccc915d7
            userCondition: null
          -
            dateAdded: '2026-03-18T20:25:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0e6b323a-67f7-4ab5-bb66-d695ee1361af # Slides
            handle: null
            instructions: 'Add slides here. Each slide contains its own text, buttons, and background asset.'
            label: 'Hero Slides'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 947f6df8-b1f6-486f-bcc0-45774dd588c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-17T17:21:12+00:00'
            elementCondition: null
            heading: 'Services Section'
            type: craft\fieldlayoutelements\Heading
            uid: dc15b568-f1eb-4bd9-95a3-c5eb7a25e2bd
            userCondition: null
          -
            dateAdded: '2025-05-09T22:17:20+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: servicesSubHead
            instructions: null
            label: 'Services Sub Head'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8616afc2-9abf-40f6-8ad4-bfecee158da8
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-26T05:51:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: servicesHead
            instructions: null
            label: 'Services Head'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7df86719-f2be-407a-aa55-d39fcfb4888d
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2024-11-26T05:51:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: servicesBody
            instructions: null
            label: 'Services Body'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 03cde428-993b-4659-9ae5-a250bef25995
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T05:51:55+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: de8eaa2e-a42a-4ec2-8e1c-8c7162ec8f4e # Services
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6bea7138-c395-486c-bfd6-e50a0b510f1f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-01-17T17:21:12+00:00'
            elementCondition: null
            heading: 'Testimonials Section'
            type: craft\fieldlayoutelements\Heading
            uid: 31ebea87-3a2e-4d00-8f3e-895e72c6b354
            userCondition: null
          -
            dateAdded: '2024-11-26T19:07:29+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ad3690bb-2435-4add-aeea-6a20d04193ff # Testimonials
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ebe32c3-813f-45c8-9583-bf38423c61f3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d411dded-f118-468e-b95c-f68ee5dde2d9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-11-26T05:30:03+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 451ebed9-368d-4404-a7f4-1c565c0dfc4a # Color
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 788f5aa5-4cdf-4696-bcf3-77c383426c53
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 0cbb1a0c-75b5-45c9-90e2-1bf0f588f888
        userCondition: null
    thumbFieldKey: null
handle: company
hasTitleField: true
icon: null
name: Company
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
