color: null
fieldLayouts:
  49ba564f-203a-4776-b36d-426ece38e970:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-06T04:40:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 01a1f3bd-08d6-49ce-a7cd-869e62b5a84c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-06T04:41:44+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9a1a1e19-d04d-4dab-9010-79d77d0f6c00
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 77f1da88-bd03-4c2f-a7c7-8aae53e7d247
        userCondition: null
handle: feature
hasTitleField: true
icon: null
name: Feature
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
