allowLineBreaksInTitles: false
color: teal
description: null
fieldLayouts:
  bec3281c-e0b6-439b-8e66-efd4a59d56f4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-18T21:10:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0437d47d-57e9-4bab-a8d3-ad35285240f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-18T21:10:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ae97b4e4-7938-4735-b734-84f98ec34af2 # Banner Buttons
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae78e4b7-e4f8-42b2-b3e9-5d2fcb1b4921
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-18T21:10:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9148b7f3-25e6-4d34-9292-7133658e1eed
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 026b3b14-7a71-4d54-a168-f400daa10cb1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-18T21:10:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bda53640-24b3-44f4-8c8b-ee991f1addba
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5b25eff-3946-4f3b-8f5b-411becb7651e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-18T21:10:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4986ae78-9ffa-41e9-ab3b-91e866576fd5 # Max Width
            handle: bannerMaxWidth
            instructions: null
            label: 'Max Width'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82673f58-62d2-4495-954c-e8688830b94f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-18T21:10:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f4540b83-421e-4a47-b91d-c09c70b4e12a # Margin Top
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c98590fa-7784-4299-b830-2cb05d787fd6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-18T21:10:00+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4a61545b-26f4-4008-8c2f-eb15c898b03f # Margin Bottom
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e40fd7a8-d090-40f5-8baa-c005d479925a
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 63f729d9-aa73-4a1a-b98e-7e493cdc50b7
        userCondition: null
    thumbFieldKey: null
handle: heroSlide
hasTitleField: false
icon: display
name: 'Hero Slide'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
