color: pink
fieldLayouts:
  7f6e1801-acd0-4fff-aa9a-86faaf218a59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T02:08:33+00:00'
            elementCondition: null
            fieldUid: 7fe80a9d-2822-4ed3-8d83-f89f27f75731 # Asset
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 224a4a71-3293-47b1-987a-79ec6faf851b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6f32b734-663b-4908-9926-0df03087ca83
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T04:43:51+00:00'
            elementCondition: null
            fieldUid: 451ebed9-368d-4404-a7f4-1c565c0dfc4a # Color
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f24047be-336f-4f5c-8059-03d6010b2d72
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: 1ebcb25d-4069-442b-84c9-b8c38d9f7193
        userCondition: null
handle: masonryGridBlock
hasTitleField: false
icon: objects-column
name: 'Masonry Grid Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
