color: purple
fieldLayouts:
  ccae7631-f804-4a5c-a3cb-596ffd7f8978:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T02:07:19+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0bb6651-04f1-46c9-b56d-338199065ec1
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a77d09e1-31f2-443e-8ea2-d2c5843ab95b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-04T04:43:16+00:00'
            elementCondition: null
            fieldUid: 451ebed9-368d-4404-a7f4-1c565c0dfc4a # Color
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f1ac14d-b468-486f-ac52-c9481fa77611
            userCondition: null
            warning: null
            width: 100
        name: Settings
        uid: d6a21848-09fc-405b-9e91-1a861a7e9a8d
        userCondition: null
handle: pullQuoteBlock
hasTitleField: false
icon: quotes
name: 'Pull Quote Block'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
