color: null
fieldLayouts:
  c48e69ee-5b64-4628-93af-4c06138e874c:
    cardView:
      - 'layoutElement:ed470e98-c60c-4f41-871b-d31f384d72b3'
      - 'layoutElement:44c38f86-7bc4-4192-a9ba-a6a8379e61ee'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-26T19:00:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Name
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0991dac0-a680-4691-9ef6-fb45df32cdcf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T19:05:37+00:00'
            elementCondition: null
            fieldUid: 8b656877-6f15-45aa-87d7-feb1d95ce5c2 # Plain Text
            handle: role
            includeInCards: true
            instructions: null
            label: Role
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed470e98-c60c-4f41-871b-d31f384d72b3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-26T19:05:37+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: quote
            includeInCards: true
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 44c38f86-7bc4-4192-a9ba-a6a8379e61ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 54be050a-73c8-47ef-b265-add00b5b2a0c
        userCondition: null
handle: testimonial
hasTitleField: true
icon: null
name: Testimonial
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
