css: ".ck.ck-content .h1 {\r\n    font-size: 6.25rem;\r\n}\r\n.ck.ck-content .h2 {\r\n    font-size: 2.5rem;\r\n}\r\n.ck.ck-content .h3 {\r\n    font-size: 1.875rem;\r\n}\r\n.ck.ck-content .h4 {\r\n    font-size: 1.375rem;\r\n}"
headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Simple
options:
  alignment:
    options:
      - left
      - center
      - right
  style:
    definitions:
      -
        classes:
          - h1
        element: h1
        name: h1
      -
        classes:
          - h2
        element: h1
        name: h2
      -
        classes:
          - h3
        element: h1
        name: h3
      -
        classes:
          - h4
        element: h1
        name: h4
      -
        attributes:
          class: col-span-1
        element:
          - p
          - h1
          - h2
          - h3
          - h4
          - h5
          - h6
          - a
          - img
          - figure
        name: 'Column Span 1'
toolbar:
  - heading
  - '|'
  - alignment
  - bold
  - underline
  - italic
  - fontColor
  - link
  - insertImage
  - mediaEmbed
  - bulletedList
  - numberedList
  - style
