defaultPlacement: end
fieldLayouts:
  f7aef625-0a8f-421c-959f-9211a4618428:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-03T19:30:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 8b544dea-7d97-4dcf-a206-7d22a45d6424
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-03T20:03:36+00:00'
            elementCondition: null
            fieldUid: 5e876e9e-c27f-47f3-ade9-0e2b65433348 # Text
            handle: null
            instructions: null
            label: Description
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5fde321-d35f-450b-9477-1159e5ae8669
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d5fbc8c8-5653-4746-914c-990720d06db1
        userCondition: null
handle: staff
name: Staff
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # Crosby Resource Management
    hasUrls: true
    template: staff-categories/_category.twig
    uriFormat: 'staff-categories/{slug}'
structure:
  maxLevels: 1
  uid: 4fcb7fb1-2112-4b08-a23c-ebeb66faafab
