altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  1f8547c8-7f19-4d4e-9cef-f772c7b66f3c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-04T02:16:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 3956f7e2-0874-4d55-8a8f-48c167a4f055
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e3d60e9-5e97-4fc4-acbc-9c1fa706957a
        userCondition: null
fs: uploads
handle: history
name: History
sortOrder: 14
subpath: history
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
