altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  3a52392c-1b94-4039-863b-ffffc8985a23:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-10T00:50:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: be97dda5-4e05-4546-b786-ee121f0e3edd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ec6ae079-b3f4-4e8d-9898-40442d16ca42
        userCondition: null
fs: uploads
handle: shapeFiles
name: 'Shape Files'
sortOrder: 15
subpath: shape
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
