altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  be2e592a-4303-41b5-b6ff-b59aec0afc44:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T04:35:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 45758bd5-820c-4829-8602-cda548c8b06c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f9b9e55a-db69-490f-9449-c26978f0275f
        userCondition: null
fs: uploads
handle: staff
name: Staff
sortOrder: 12
subpath: staff
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: transforms
