columnSuffix: null
handle: entries
instructions: null
name: Entries
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  defaultPlacement: end
  maintainHierarchy: false
  maxRelations: 3
  minRelations: 0
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedEntries: true
  showUnpermittedSections: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards-grid
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
