columnSuffix: null
handle: entries
instructions: null
name: Entries
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 3
  minRelations: 0
  selectionLabel: null
  showCardsInGrid: true
  showSiteMenu: true
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
