columnSuffix: null
handle: landBlocks
instructions: null
name: 'Land Blocks'
searchable: false
settings:
  createButtonLabel: 'New block'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - a76ef161-fb46-4a93-b50b-110ab2cee1b9 # Land Block
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards-grid
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
