columnSuffix: null
handle: projectImages
instructions: 'Upload images for the project.'
name: 'Project Images'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
    - video
  branchLimit: null
  defaultUploadLocationSource: 'volume:0df67807-28de-4196-83d0-7659095a96c0'
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:0df67807-28de-4196-83d0-7659095a96c0'
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: true
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
