columnSuffix: null
handle: services
instructions: null
name: Services
searchable: false
settings:
  createButtonLabel: 'New Service'
  defaultIndexViewMode: cards
  entryTypes:
    - 26bea4ed-bac2-4732-9ac4-fb8cb523da52 # Service
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
