columnSuffix: null
handle: shapeFile
instructions: 'Upload a .shp file to populate the map.'
name: 'Shape File'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:ebc5822f-5362-4f1c-a6b8-37a17ea08cf0' # Shape Files
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:0524ce74-5809-4227-9995-c07e31fcd67f' # General
  restrictedLocationSubpath: null
  selectionLabel: 'Add files'
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:ebc5822f-5362-4f1c-a6b8-37a17ea08cf0' # Shape Files
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards-grid
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
