columnSuffix: null
handle: slideMatrix
instructions: null
name: Slide
searchable: false
settings:
  createButtonLabel: 'New block'
  defaultIndexViewMode: cards
  entryTypes:
    - 84b49fbd-67b9-4021-9790-4d862971a1fb # Text
    - 98531642-0cb8-4a38-a70c-ddd5f537d751 # Buttons
    - e6b912d1-5313-4b23-b098-f3ef208c3d70 # Asset
    - f51bd3ce-5a3a-4094-b3b0-9304dfe18b7d # Caption
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
