columnSuffix: null
handle: staffCategory
instructions: 'Choose a staff category for this staff member.'
name: 'Staff Category'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: null
  showCardsInGrid: true
  showSiteMenu: true
  source: 'group:bf576820-9e89-40b9-a7c5-82be152e232e' # Staff
  targetSiteId: null
  validateRelatedElements: false
  viewMode: cards
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
