columnSuffix: null
handle: testimonials
instructions: null
name: Testimonials
searchable: false
settings:
  createButtonLabel: 'New Testimonial'
  defaultIndexViewMode: cards
  entryTypes:
    - 0e035fe3-0cf6-480e-82fe-d52cc928e650 # Testimonial
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
