columnSuffix: null
handle: textAlignment
instructions: null
name: 'Text Alignment'
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - 'Top Left'
        -
          - value
          - 'justify-start items-start'
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Top Center'
        -
          - value
          - top-center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Top Right'
        -
          - value
          - top-right
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Center Left'
        -
          - value
          - center-left
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Center Center'
        -
          - value
          - center-center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Center Right'
        -
          - value
          - center-right
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Left'
        -
          - value
          - 'justify-start items-end'
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'Bottom Center'
        -
          - value
          - bottom-center
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Bottom Right'
        -
          - value
          - bottom-right
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
