defaultPlacement: end
enableVersioning: true
entryTypes:
  - f9c5fde4-c87c-45b1-8052-613600b09751 # Land & Minerals
handle: land
maxAuthors: 1
name: 'Land & Minerals'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6974ec26-6de3-4cbe-87a2-c5363298442b: # Crosby
    enabledByDefault: true
    hasUrls: true
    template: _pages/land
    uriFormat: 'land-minerals/{slug}'
structure:
  maxLevels: null
  uid: e4055b41-ef94-480a-872c-e99a5e5ccb8d
type: structure
