tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-23T16:57:06-07:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: befc0175-4575-487b-8f11-9f785f027e5f
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2024-12-23T16:57:06-07:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: e7d996a5-794a-409a-8b4c-ec9e5264814c
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-23T16:57:06-07:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: e3b18d1e-52f4-46d9-b3fd-91825929802b
        userCondition: null
        warning: null
    name: Content
    uid: 9946b01a-55b1-446b-ba6f-4a1df596b97f
    userCondition: null
